from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


AnalysisTaskType = Literal[
    "trend_analysis",
    "comparison_analysis",
    "distribution_analysis",
    "resume_recovery",
    "unknown",
]


class AnalysisTaskRequest(BaseModel):
    task_id: str = Field(..., description="Task identifier generated by Java")
    trace_id: str = Field(..., description="Trace identifier spanning Java and Python")
    tenant_id: str
    user_id: str
    question: str
    dataset_ids: list[str] = Field(default_factory=list)
