from __future__ import annotations

from langgraph.graph import END, START, StateGraph

from agent_backend.orchestration.checkpoint import capture_checkpoint, restore_checkpoint
from agent_backend.orchestration.state import AgentState


def _load_context(state: AgentState) -> AgentState:
    state["plan"] = ["inspect schema", "generate read-only SQL", "summarize findings"]
    state["node_id"] = "load_context"
    state["node_name"] = "load_context"
    state["node_status"] = "running"
    state["resume_cursor"] = "load_context"
    return state


def _checkpoint_node(state: AgentState) -> AgentState:
    snapshot = capture_checkpoint(state, state.get("node_id", "checkpoint"))
    restored = restore_checkpoint(snapshot)
    restored["snapshot_id"] = snapshot.snapshot_id
    return restored


def _write_answer(state: AgentState) -> AgentState:
    state["final_answer"] = "Scaffold response generated by graph runtime."
    state["node_id"] = "write_answer"
    state["node_name"] = "write_answer"
    state["node_status"] = "completed"
    return state


def build_graph():
    workflow = StateGraph(AgentState)
    workflow.add_node("load_context", _load_context)
    workflow.add_node("checkpoint_node", _checkpoint_node)
    workflow.add_node("write_answer", _write_answer)
    workflow.add_edge(START, "load_context")
    workflow.add_edge("load_context", "checkpoint_node")
    workflow.add_edge("checkpoint_node", "write_answer")
    workflow.add_edge("write_answer", END)
    return workflow.compile()
